export const language = 
{
    "Arabic (Egypt)": "ar-eg",
    "Arabic (Saudi Arabia)": "ar-sa",
    "Bulgarian": "bg-bg",
    "Catalan": "ca-es",
    "Chinese (China)": "zh-cn",
    "Chinese (Hong Kong)": "zh-hk",
    "Chinese (Taiwan)": "zh-tw",
    "Croatian": "hr-hr",
    "Czech": "cs-cz",
    "Danish": "da-dk",
    "Dutch (Belgium)": "nl-be",
    "Dutch (Netherlands)": "nl-nl",
    "English (Australia)": "en-au",
    "English (Canada)": "en-ca",
    "English (Great Britain)": "en-gb",
    "English (India)": "en-in",
    "English (Ireland)": "en-ie",
    "English (United States)": "en-us",
    "Finnish": "fi-fi",
    "French (Canada)": "fr-ca",
    "French (France)": "fr-fr",
    "French (Switzerland)": "fr-ch",
    "German (Austria)": "de-at",
    "German (Germany)": "de-de",
    "German (Switzerland)": "de-ch",
    "Greek": "el-gr",
    "Hebrew": "he-il",
    "Hindi": "hi-in",
    "Hungarian": "hu-hu",
    "Indonesian": "id-id",
    "Italian": "it-it",
    "Japanese": "ja-jp",
    "Korean": "ko-kr",
    "Malay": "ms-my",
    "Norwegian": "nb-no",
    "Polish": "pl-pl",
    "Portuguese (Brazil)": "pt-br",
    "Portuguese (Portugal)": "pt-pt",
    "Romanian": "ro-ro",
    "Russian": "ru-ru",
    "Slovak": "sk-sk",
    "Slovenian": "sl-si",
    "Spanish (Mexico)": "es-mx",
    "Spanish (Spain)": "es-es",
    "Swedish": "sv-se",
    "Tamil": "ta-in",
    "Thai": "th-th",
    "Turkish": "tr-tr",
    "Vietnamese": "vi-vn"
  }
  
