export const voix = {
    'ar-eg': ['Oda'],
    'ar-sa': ['Salim'],
    'bg-bg': ['Dimo'],
    'ca-es': ['Rut'],
    'zh-cn': ['Luli', 'Shu', 'Chow', 'Wang'],
    'zh-hk': ['Jia', 'Xia', 'Chen'],
    'zh-tw': ['Akemi', 'Lin', 'Lee'],
    'hr-hr': ['Nikola'],
    'cs-cz': ['Josef'],
    'da-dk': ['Freja'],
    'nl-be': ['Daan'],
    'nl-nl': ['Lotte', 'Bram'],
    'en-au': ['Zoe', 'Isla', 'Evie', 'Jack'],
    'en-ca': ['Rose', 'Clara', 'Emma', 'Mason'],
    'en-gb': ['Alice', 'Nancy', 'Lily', 'Harry'],
    'en-in': ['Eka', 'Jai', 'Ajit'],
    'en-ie': ['Oran'],
    'en-us': ['Linda', 'Amy', 'Mary', 'John', 'Mike'],
    'fi-fi': ['Aada'],
    'fr-ca': ['Emile', 'Olivia', 'Logan', 'Felix'],
    'fr-fr': ['Bette', 'Iva', 'Zola', 'Axel'],
    'fr-ch': ['Theo'],
    'de-at': ['Lukas'],
    'de-de': ['Hanna', 'Lina', 'Jonas'],
    'de-ch': ['Tim'],
    'el-gr': ['Neo'],
    'he-il': ['Rami'],
    'hi-in': ['Puja', 'Kabir'],
    'hu-hu': ['Mate'],
    'id-id': ['Intan'],
    'it-it': ['Bria', 'Mia', 'Pietro'],
    'ja-jp': ['Hina', 'Airi', 'Fumi', 'Akira'],
    'ko-kr': ['Nari'],
    'ms-my': ['Aqil'],
    'nb-no': ['Marte', 'Erik'],
    'pl-pl': ['Julia', 'Jan'],
    'pt-br': ['Marcia', 'Ligia', 'Yara', 'Dinis', 'Leonor'],
    'pt-pt': ['Leonor'],
    'ro-ro': ['Doru'],
    'ru-ru': ['Olga', 'Marina', 'Peter'],
    'sk-sk': ['Beda'],
    'sl-si': ['Vid'],
    'es-mx': [ 'Juana', 'Silvia', 'Teresa', 'Jose'],
    'es-es': ['Camila', 'Sofia', 'Luna', 'Diego'],
    'sv-se': ['Molly', 'Hugo'],
    'ta-in': ['Sai'],
    'th-th': ['Ukrit'],
    'tr-tr': ['Omer'],
    'vi-vn': ['Chi'],
}